### PR TITLE
Replace CloudNS with DNS.WATCH

### PR DESCRIPTION
**Pull request by Angristan**
CloudNS is not working anymore, so here's a great alternative.

PR following this issue : https://github.com/privacytools-io/privacytools.io/issues/16

### CODE REVIEW

**Comment by Shifterovich** [comment]
Figured I can edit PR's code with ease. :P

**Comment by Shifterovich** [comment]
Merging, as @kewde had upvoted the issue.

**Comment by kewde** [comment]
Agreed on this merge.

**Comment by Shifterovich** [comment]
@privacytoolsIO thoughts?

**Pull request merged**
